DROP DATABASE IF EXISTS Practica2;

CREATE DATABASE Practica2 
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE Practica2;

CREATE TABLE ALUMNO(
	IDALUMNO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
	APPATERNO VARCHAR(30) NOT NULL,
	APMATERNO VARCHAR(30) NULL,
	PROMEDIO FLOAT NULL,
	FECH_INGRESO DATE NOT NULL
) ENGINE = INNODB;

INSERT INTO ALUMNO(NOMBRE,APPATERNO,APMATERNO,PROMEDIO,FECH_INGRESO) VALUES ('Blanca Jenipher','García','Montez',10,'02/02/10'),
																			('Brandon','García','Ruíz',9,'05/08/11'),
																			('Brenda','Alcantara',NULL,NULL,'05/01/14');

UPDATE ALUMNO SET PROMEDIO=8 WHERE IDALUMNO = 1;
UPDATE ALUMNO SET PROMEDIO=9 WHERE IDALUMNO = 2;

DELETE FROM ALUMNO WHERE IDALUMNO = 3;


CREATE TABLE AUTOMOVIL(
	IDAUTOMOVIL INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	MARCA VARCHAR(30) NOT NULL,
	COLOR VARCHAR(20) NOT NULL,
	PLACAS VARCHAR(10) NOT NULL
) ENGINE = INNODB;

INSERT INTO AUTOMOVIL(MODELO,MARCA,COLOR,PLACAS) VALUES ('2012','Ford','Negro','XXX-XXX'),
														('2013','Nissan','Azul','XXX-XXX'),
														('1993','Audi','Rojo','XXX-XXX'),
														('2001','BMW','Gris','XXX-XXX');

UPDATE AUTOMOVIL SET COLOR = 'Verde' WHERE IDAUTOMOVIL = 3;

/*Elimina dos autos*/
DELETE FROM AUTOMOVIL WHERE IDAUTOMOVIL BETWEEN 1 AND 2;

CREATE TABLE MATERIA(
	IDMATERIA INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
	NIVEL INTEGER NOT NULL,
	CREDITOS FLOAT NOT NULL
);

INSERT INTO MATERIA(NOMBRE,NIVEL,CREDITOS) VALUES('Bases de Datos',2,4.44);
INSERT INTO MATERIA(NOMBRE,NIVEL,CREDITOS) VALUES('Compiladores',3,4.44);
INSERT INTO MATERIA(NOMBRE,NIVEL,CREDITOS) VALUES('Anális de imágenes',3,4.44);

DELETE FROM MATERIA WHERE IDMATERIA > 1;

