DROP DATABASE IF EXISTS Practica3;

CREATE DATABASE Practica3;

USE Practica3;

CREATE TABLE CLIENTE(
	ID_CLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL, 
	APPATERNO VARCHAR(30) NOT NULL,
	APMATERNO VARCHAR(30) NOT NULL,
	RFC VARCHAR(13),
	CREDITO DECIMAL(5,2),
	DEUDA DECIMAL(5,2),
	DIRECCION VARCHAR(70) NOT NULL,
	CP INTEGER(5) NOT NULL);

INSERT INTO CLIENTE(ID_CLIENTE,NOMBRE,APPATERNO,APMATERNO,RFC,CREDITO,DEUDA,DIRECCION,CP)
	    VALUES (1,'Gamaliel','Jimenez','Garcia','JIGE930831',500,400,'DatosDireccion1',57770),
		   (2,'Eduardo','Jimenez','Garcia','JIGE930831',200,100,'DatosDireccion2',57900);


-- Muestra nombre, apellido paterno y materno
SELECT NOMBRE,APPATERNO,APMATERNO FROM CLIENTE;

-- Muestra Id,Nombre,ApPaterno y RFC 
SELECT ID_CLIENTE,NOMBRE,APPATERNO,RFC FROM CLIENTE;

-- Muestra ApPaterno y los datos de dirección
SELECT APPATERNO,DIRECCION FROM CLIENTE;

-- Muestra ApMaterno, nombre, credito y deuda
SELECT APMATERNO,NOMBRE,CREDITO,DEUDA FROM CLIENTE;

-- Muestra todos los campos
SELECT * FROM CLIENTE;

SELECT CP AS 'REGISTRO FEDERAL DE CONTRIBUYENTE' FROM CLIENTE; 

-- Muestra el apellido paterno como A.paterno, el apellido materno como A.Materno y el nombr FROM CLIENTE;

-- Muestra el nombre con el apellido paterno.
SELECT APPATERNO AS 'A.Paterno', APMATERNO AS 'A.Materno', NOMBRE FROM CLIENTE;

-- Muestra direccion, nombre y el RFC com registro de contribuyentes
SELECT DIRECCION,NOMBRE, RFC AS 'REGISTRO DE CONTRIBUYENTES' FROM CLIENTE;

-- Muestra el nombre con el apellido paterno.
SELECT CONCAT(NOMBRE,' ',APPATERNO) AS 'NOMBRE COMPLETO' FROM CLIENTE;

SELECT CONCAT('El cliente [',NOMBRE,'] se apellida [',APPATERNO,']') AS REPORTE FROM CLIENTE;

SELECT CONCAT('[',NOMBRE,'] vive en [',DIRECCION,']') AS REPORTE FROM CLIENTE;

SELECT CREDITO-DEUDA AS 'CREDITO DISPONIBLE' FROM CLIENTE;

SELECT (CREDITO-DEUDA)*0.15 AS '15% DE LA DEUDA' FROM CLIENTE;

SELECT NOMBRE,DEUDA,(DEUDA)*.10  AS '10% DE LA DEUDA',(DEUDA)*1.10 'INCREMENTO' FROM CLIENTE;

SELECT DEUDA/6 AS 'DEUDA EN 6 MESES', DEUDA/12 AS 'DEUDA EN 12 MESES', DEUDA/24 AS 'DEUDA EN 24 MESES' FROM CLIENTE;

SELECT NOMBRE,DEUDA,(DEUDA/6)*0.10 AS 'DEUDA EN 6 MESES CON CARGO DEL 10%' FROM CLIENTE;

SELECT NOMBRE,DEUDA-(DEUDA*0.30) AS 'DEUDA CON DESCUENTO DEL 10%' FROM CLIENTE;

SELECT (DEUDA-(DEUDA*0.30))/6 AS 'DEUDA A 6 MESES', (DEUDA-(DEUDA*0.30))/12 AS 'DEUDA A 12 MESES', (DEUDA-(DEUDA*0.30))/24 AS 'DEUDA A 24 MESES' FROM CLIENTE;

SELECT CONCAT('EL CREDITO DE [',NOMBRE,'] ES DE [',CREDITO,']') AS 'REPORTE CREDITO' FROM CLIENTE;

SELECT CONCAT('[',NOMBRE,'] TIENE UN CREDITO DE [',CREDITO,'] Y DEBE [',DEUDA,'], POR TANTO PUEDE PEDIR OTRO CREDITO DE HASTA ',CREDITO-DEUDA) FROM CLIENTE;

SELECT CONCAT('[',NOMBRE,'] EN UN CREDITO DE 6 MESES TIENE QUE PAGAR UN TOTAL DE [',DEUDA,'] POR TANTO PAGARA MENSUALMENTE [',DEUDA/6,']') FROM CLIENTE;
