DROP DATABASE IF EXISTS Escuela;

CREATE DATABASE Escuela;

USE Escuela;

CREATE TABLE PROFESOR(
	IDPROFESOR INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
	FECH_NAC DATE NOT NULL,
	FECH_ING DATE NOT NULL,
	SALARIO FLOAT NOT NULL
);

CREATE TABLE SALON(
	IDSALON INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CODIGO VARCHAR(4) NOT NULL,
	UBICACION VARCHAR(50) NOT NULL
);

DROP DATABASE IF EXISTS TallerMecanico;

CREATE DATABASE TallerMecanico;

USE TallerMecanico;

CREATE TABLE MECANICO(
	IDMECANICO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
	FECH_ING DATE NOT NULL
);

CREATE TABLE REFACCIONES(
	IDREFACCION INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
	FECH_LLEGADA DATE NOT NULL,
	FECH_GARANTIA DATE NOT NULL
);

CREATE TABLE AUTOMOVIL(
	IDAUTO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) NOT NULL,
	MODELO VARCHAR(30) NOT NULL,
	DESCRIPCION_FALLAS LONGTEXT NOT NULL
)